### ISSUE TITLE
Server wont open with Dungeons, Dragons and Space Shuttles modpack

### ISSUE THREAD

**Issue by MiniGPT** [AlexProgrammerDE/balena-minecraft-server#192]
While using this modpack (https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles), this error happens:

<mc-server> Starting balenaMinecraftServer...
<mc-server> 
<mc-server> Config already copied
<mc-server> Checking server JAR... Found a valid server file. It's called: forge-1.12.jar
<mc-server> minecraft_server.1.12.2.jar
<mc-server> paper.jar. Use ENABLE_UPDATE to update.
<mc-server> Starting JAR file with: 4G of RAM
<mc-server> A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
<mc-server> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<mc-server> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
<mc-server> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<mc-server> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
<mc-server> 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
<mc-server> 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
<mc-server> Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
<mc-server> 	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
<mc-server> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
<mc-server> 	... 6 more
<mc-server> Setting device hostname to: balenaminecraftserver

I used the server files from the modpack website, with forge 1.12.

**Comment by MiniGPT** [comment]
Found a fix.
