### ISSUE TITLE
[BUG] Invalid or corrupt jarfile paper.jar

### ISSUE THREAD

**Issue by AnthonyVadala** [AlexProgrammerDE/balena-minecraft-server#4]
**Describe the Bug**
When starting the Minecraft service from balena dashboard the Logs panel show:
 ```
Starting jar file with 2GB of RAM.
Error: Invalid or corrupt jarfile paper.jar
```

**To Reproduce**
1. `git clone git@github.com:AlexProgrammerDE/balena-minecraft-server.git`
2. `balena login`
3. `balena push Minecraft-Server`
4. Open balena dashboard and check Logs

**Expected behavior**
The Minecraft service to start without error.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1624604/74988756-b9b1cf00-540c-11ea-819c-5f698b9cb0fb.PNG)

**Raspberry Pi (please complete the following information):**
 - OS: balenaOS 2.47.0+rev1

**Minecraft:**
 - Minecraft Edition Java Edition

**Comment by AlexProgrammerDE** [comment]
@AnthonyVadala what happens, when you set `ENABLE_UPDATE` to true?

**Comment by AnthonyVadala** [comment]
> @AnthonyVadala what happens, when you set `ENABLE_UPDATE` to `true`?

This resolves the issue!

**Comment by AlexProgrammerDE** [comment]
@AnthonyVadala the problem was that your device had no internet connection on the first boot. It tried to download the paper.jar, but failed. It left behind a 0KB file. With the var set it tries on every boot to get the file. You should delete this var now. If you dont do this can the error occur again if the device has no internet connection. I will add code in #5 ehich ensures that the file is 100% downloaded.

**Comment by chazzytho** [comment]
Hi, I have the same problem but setting `ENABLE_UPDATE` to `true` isn't working.

Is there maybe some other fix to this? The server was running fine until I changed one variable in a mod, which has been undone.

**Comment by AlexProgrammerDE** [comment]
@chazzytho can you open a separate issue for this?

**Comment by FreshSoul** [comment]
> @AnthonyVadala what happens, when you set `ENABLE_UPDATE` to `true`?

How to do this?

**Comment by AlexProgrammerDE** [comment]
@FreshSoul you can do this in the Enviroment Variable section in the Cloud dashboard.

**Comment by FreshSoul** [comment]
@AlexProgrammerDE, Sorry, this is certainly off topic, but can you please tell me how to change the default port (22)?

**Comment by FreshSoul** [comment]
also thanks for prompting

**Comment by AlexProgrammerDE** [comment]
@FreshSoul i think for doing that you have to app the `-p` parameter to the end line of the start.sh file in scp cpntainer. By the way why do you need that?

**Comment by FreshSoul** [comment]
@AlexProgrammerDE I want to have remote access to the server files, but since my router has port 22 by default, and also it cannot be changed, and therefore I needed it

**Comment by FreshSoul** [comment]
@AlexProgrammerDE and something else, please tell me, this is normal? Unable to determine local host IP, please set server-ip in server.properties: balenaminecraftserver: balenaminecraftserver: No address associated with hostname

**Comment by AlexProgrammerDE** [comment]
@FreshSoul yes this is normal. But it should work with it.

**Comment by FreshSoul** [comment]
@AlexProgrammerDE i have the last question for you, Spider mode enabled. Check if remote file exists.
10.04.20 20:01:09 (+0300)  wifi-connect  --2020-04-10 17:01:09--  http://google.com/
10.04.20 20:01:09 (+0300)  wifi-connect  Resolving google.com (google.com)... 172.217.20.206, 2a00:1450:401b:803::200e
10.04.20 20:01:09 (+0300)  wifi-connect  Connecting to google.com (google.com)|172.217.20.206|:80... connected.
10.04.20 20:01:09 (+0300)  wifi-connect  HTTP request sent, awaiting response... 301 Moved Permanently
10.04.20 20:01:09 (+0300)  wifi-connect  Location: http://www.google.com/ [following]
10.04.20 20:01:09 (+0300)  wifi-connect  Spider mode enabled. Check if remote file exists.
10.04.20 20:01:09 (+0300)  wifi-connect  --2020-04-10 17:01:09--  http://www.google.com/
10.04.20 20:01:09 (+0300)  wifi-connect  Resolving www.google.com (www.google.com)... 216.58.209.4, 2a00:1450:401b:808::2004
10.04.20 20:01:09 (+0300)  wifi-connect  Connecting to www.google.com (www.google.com)|216.58.209.4|:80... connected.
10.04.20 20:01:09 (+0300)  wifi-connect  HTTP request sent, awaiting response... 200 OK
10.04.20 20:01:09 (+0300)  wifi-connect  Length: unspecified [text/html]
10.04.20 20:01:09 (+0300)  wifi-connect  Remote file exists and could contain further links,
10.04.20 20:01:09 (+0300)  wifi-connect  but recursion is disabled -- not retrieving.
10.04.20 20:01:09 (+0300)  wifi-connect  
10.04.20 20:01:09 (+0300)  wifi-connect  Skipping WiFi Connect, all is this normal?

**Comment by AlexProgrammerDE** [comment]
@FreshSoul yes this is a part of the wifi connect container. It checks if there is a internet connection. If it cant connect it opens a wifi. You can read more about it here: https://github.com/balena-io/wifi-connect

**Comment by xaned41390** [comment]
Hello @AlexProgrammerDE, i have a question for you, 
if I bring my raspberry pi  to my other house, then how can I connect it to wi-fi?

**Comment by AlexProgrammerDE** [comment]
@xaned41390 can you please open for this a separat issue?

**Comment by FreshSoul** [comment]
@AlexProgrammerDE I have a question for you, is it possible to transfer the server to another version of minecraft?

**Comment by AlexProgrammerDE** [comment]
@FreshSoul do you mean newer or older?

**Comment by FreshSoul** [comment]
older

**Comment by AlexProgrammerDE** [comment]
@FreshSoul so should first download the jar file of the older version. Then transfer it to the Pi via SCP. The last thing is setting the `JAR_FILE` enviroment variable to the file you just transferred. (Something like `paper.jar`)

**Comment by FreshSoul** [comment]
> @FreshSoul so you should first download the jar file of the older version. Then transfer it to the Pi via SCP. The last thing is setting the `JAR_FILE` enviroment variable to the file you just transferred. (Something like `paper.jar`)

@AlexProgrammerDE 
can you tell me more about this?

**Comment by AlexProgrammerDE** [comment]
@FreshSoul get bukkit provides builds of all versions of minecraft: https://getbukkit.org/download/spigot
To be able to use the jar file you have to transfer it via SCP to the PI and delete the old file. 
After that you should set the name of the new file. The value should be somethin like `spigot-xxx.jar`.
The variable to set this is `JAR_FILE` and it can be set via the cloud dashboard. After a restart should your file start and you are able to join it. 👍

**Comment by FreshSoul** [comment]
Thanks, I just don’t know where the old file is

**Comment by AlexProgrammerDE** [comment]
@FreshSoul the file is named `paper.jar`. Paper is a efficient spigot fork.

**Comment by FreshSoul** [comment]
and then insert the JAR FILE to true variable?

**Comment by FreshSoul** [comment]
or i am very stupid

**Comment by AlexProgrammerDE** [comment]
@FreshSoul the value of `JAR_FILE` should be the name of the file. Including the `.jar` part.

**Comment by FreshSoul** [comment]
ok thanks

**Comment by FreshSoul** [comment]
I added a spigot version file instead of paper. jar but after rebooting the server again downloaded this file

**Comment by AlexProgrammerDE** [comment]
@FreshSoul can you please delete the ENABLE_UPDATE variable?

**Comment by FreshSoul** [comment]
Starting minecraft server version 1.15.2
 mc-server  [: Loading properties
: This server is running Paper version git-Paper-176 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by AlexProgrammerDE** [comment]
@FreshSoul and of course delete the paper.jar file

**Comment by FreshSoul** [comment]
Starting jar file with 2GB of RAM.
Error: Unable to access jarfile paper.jar

**Comment by AlexProgrammerDE** [comment]
@FreshSoul that indicates that the `JAR_FILE` variable isn't set.

**Comment by FreshSoul** [comment]
I created a JAR_FILE variable with the value spigot-1.12.2.jar

**Comment by AlexProgrammerDE** [comment]
@FreshSoul can you please send me a screenshot?

**Comment by FreshSoul** [comment]
![balenaCloud _ icy-pond - Opera 12 04 2020 22_54_48](https://user-images.githubusercontent.com/63451568/79078403-cbc73400-7d10-11ea-81bd-3d936fc49c29.png)

**Comment by FreshSoul** [comment]
![not connected - Bitvise SFTP 12 04 2020 22_53_47](https://user-images.githubusercontent.com/63451568/79078408-d71a5f80-7d10-11ea-998d-326dd0a36794.png)
![balenaCloud _ icy-pond - Opera 12 04 2020 22_55_33](https://user-images.githubusercontent.com/63451568/79078416-e1d4f480-7d10-11ea-92f1-654189a456ab.png)

**Comment by AlexProgrammerDE** [comment]
@FreshSoul can you please try a restart?

**Comment by FreshSoul** [comment]
Starting jar file with 2GB of RAM.
 mc-server  Loading libraries, please wait...
[20:06:08 INFO]: Starting minecraft server version 1.12.2
[20:06:08 INFO]: Loading properties
[20:06:08 INFO]: Default game type: SURVIVAL
[20:06:09 INFO]: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:06:09 INFO]: Server Ping Player Sample Count: 12
[20:06:09 INFO]: Using 4 threads for Netty based IO
[20:06:09 INFO]: Debug logging is disabled
[20:06:09 INFO]: Generating keypair
 wifi-connect  Spider mode enabled. Check if remote file exists.
 wifi-connect  --2020-04-12 20:06:09--  http://google.com/
 wifi-connect  Resolving google.com (google.com)... 172.217.20.174, 2a00:1450:401b:802::200e
 wifi-connect  Connecting to google.com (google.com)|172.217.20.174|:80... connected.
 wifi-connect  HTTP request sent, awaiting response... 301 Moved Permanently
 wifi-connect  Location: http://www.google.com/ [following]
 wifi-connect  Spider mode enabled. Check if remote file exists.
 wifi-connect  --2020-04-12 20:06:10--  http://www.google.com/
 wifi-connect  Resolving www.google.com (www.google.com)... 216.58.215.68, 2a00:1450:401b:806::2004
 wifi-connect  Connecting to www.google.com (www.google.com)|216.58.215.68|:80... connected.
 wifi-connect  HTTP request sent, awaiting response... 200 OK
 wifi-connect  Length: unspecified [text/html]
 wifi-connect  Remote file exists and could contain further links,
 wifi-connect  but recursion is disabled -- not retrieving.
 wifi-connect  
 wifi-connect  Skipping WiFi Connect
[20:06:10 INFO]: Starting Minecraft server on *:25565
[20:06:10 INFO]: Using default channel type
[20:06:10 INFO]: Set PluginClassLoader as parallel capable
[20:06:10 INFO]: [WorldEdit] Loading WorldEdit v7.1.0;8e55131
[20:06:12 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@6a82072d]
[20:06:12 INFO]: [WorldGuard] Loading WorldGuard v7.0.2-SNAPSHOT;bf2593e
[20:06:12 INFO]: [WorldEdit] Enabling WorldEdit v7.1.0;8e55131
[20:06:12 INFO]: WEPIF: Using the Bukkit Permissions API.
[20:06:12 ERROR]: [WorldEdit] Plugin WorldEdit v7.1.0;8e55131 has failed to register events for class com.sk89q.worldedit.bukkit.WorldEditListener because org/bukkit/event/player/PlayerCommandSendEvent does not exist.
[20:06:12 ERROR]: Error occurred while enabling WorldEdit v7.1.0;8e55131 (Is it up to date?)
 mc-server  java.lang.NoSuchMethodError: 'boolean org.bukkit.Material.isLegacy()'
 mc-server      at com.sk89q.worldedit.bukkit.WorldEditPlugin.initializeRegistries(WorldEditPlugin.java:184) ~[?:?]
 mc-server      at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:144) ~[?:?]
 mc-server      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at java.lang.Thread.run(Thread.java:834) [?:?]
[20:06:12 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[20:06:12 WARN]: The server will make no attempt to authenticate usernames. Beware.
[20:06:12 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[20:06:12 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[20:06:12 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[20:06:12 INFO]: Preparing level "world"
[20:06:13 INFO]: -------- World Settings For [world] --------
[20:06:13 INFO]: Cactus Growth Modifier: 100%
[20:06:13 INFO]: Cane Growth Modifier: 100%
[20:06:13 INFO]: Melon Growth Modifier: 100%
[20:06:13 INFO]: Mushroom Growth Modifier: 100%
[20:06:13 INFO]: Pumpkin Growth Modifier: 100%
[20:06:13 INFO]: Sapling Growth Modifier: 100%
[20:06:13 INFO]: Wheat Growth Modifier: 100%
[20:06:13 INFO]: NetherWart Growth Modifier: 100%
[20:06:13 INFO]: Vine Growth Modifier: 100%
[20:06:13 INFO]: Cocoa Growth Modifier: 100%
[20:06:13 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[20:06:13 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:06:13 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:06:13 INFO]: Random Lighting Updates: false
[20:06:13 INFO]: Structure Info Saving: true
[20:06:13 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[20:06:13 INFO]: Max TNT Explosions: 100
[20:06:13 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:06:13 INFO]: Mob Spawn Range: 8
[20:06:13 INFO]: Item Despawn Rate: 6000
[20:06:13 INFO]: Item Merge Radius: 2.5
[20:06:13 INFO]: Arrow Despawn Rate: 1200
[20:06:13 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:06:13 INFO]: View Distance: 10
[20:06:13 INFO]: Experience Merge Radius: 3.0
[20:06:13 INFO]: Zombie Aggressive Towards Villager: true
[20:06:13 INFO]: Nerfing mobs spawned from spawners: false
[20:06:14 INFO]: -------- World Settings For [world_nether] --------
[20:06:14 INFO]: Cactus Growth Modifier: 100%
[20:06:14 INFO]: Cane Growth Modifier: 100%
[20:06:14 INFO]: Melon Growth Modifier: 100%
[20:06:14 INFO]: Mushroom Growth Modifier: 100%
[20:06:14 INFO]: Pumpkin Growth Modifier: 100%
[20:06:14 INFO]: Sapling Growth Modifier: 100%
[20:06:14 INFO]: Wheat Growth Modifier: 100%
[20:06:14 INFO]: NetherWart Growth Modifier: 100%
[20:06:14 INFO]: Vine Growth Modifier: 100%
[20:06:14 INFO]: Cocoa Growth Modifier: 100%
[20:06:14 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[20:06:14 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:06:14 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:06:14 INFO]: Random Lighting Updates: false
[20:06:14 INFO]: Structure Info Saving: true
[20:06:14 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[20:06:14 INFO]: Max TNT Explosions: 100
[20:06:14 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:06:14 INFO]: Mob Spawn Range: 8
[20:06:14 INFO]: Item Despawn Rate: 6000
[20:06:14 INFO]: Item Merge Radius: 2.5
[20:06:14 INFO]: Arrow Despawn Rate: 1200
[20:06:14 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:06:14 INFO]: View Distance: 10
[20:06:14 INFO]: Experience Merge Radius: 3.0
[20:06:14 INFO]: Zombie Aggressive Towards Villager: true
[20:06:14 INFO]: Nerfing mobs spawned from spawners: false
[20:06:15 INFO]: -------- World Settings For [world_the_end] --------
[20:06:15 INFO]: Cactus Growth Modifier: 100%
[20:06:15 INFO]: Cane Growth Modifier: 100%
[20:06:15 INFO]: Melon Growth Modifier: 100%
[20:06:15 INFO]: Mushroom Growth Modifier: 100%
[20:06:15 INFO]: Pumpkin Growth Modifier: 100%
[20:06:15 INFO]: Sapling Growth Modifier: 100%
[20:06:15 INFO]: Wheat Growth Modifier: 100%
[20:06:15 INFO]: NetherWart Growth Modifier: 100%
[20:06:15 INFO]: Vine Growth Modifier: 100%
[20:06:15 INFO]: Cocoa Growth Modifier: 100%
[20:06:15 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[20:06:15 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:06:15 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:06:15 INFO]: Random Lighting Updates: false
[20:06:15 INFO]: Structure Info Saving: true
[20:06:15 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[20:06:15 INFO]: Max TNT Explosions: 100
[20:06:15 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:06:15 INFO]: Mob Spawn Range: 8
[20:06:15 INFO]: Item Despawn Rate: 6000
[20:06:15 INFO]: Item Merge Radius: 2.5
[20:06:15 INFO]: Arrow Despawn Rate: 1200
[20:06:15 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:06:15 INFO]: View Distance: 10
[20:06:15 INFO]: Experience Merge Radius: 3.0
[20:06:15 INFO]: Zombie Aggressive Towards Villager: true
[20:06:15 INFO]: Nerfing mobs spawned from spawners: false
[20:06:15 INFO]: Preparing start region for level 0 (Seed: 7134749218273720341)
[20:06:15 WARN]: Could not set level chunk heightmap, array length is 0 instead of 256
[20:06:15 ERROR]: Encountered an unexpected exception
 mc-server  java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
 mc-server      at net.minecraft.server.v1_12_R1.NibbleArray.<init>(NibbleArray.java:14) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:402) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:94) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:72) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:21) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
 mc-server      at java.lang.Thread.run(Thread.java:834) [?:?]
[20:06:15 ERROR]: This crash report has been saved to: /usr/src/serverfiles/./crash-reports/crash-2020-04-12_20.06.15-server.txt
[20:06:15 INFO]: Stopping server
[20:06:15 INFO]: [WorldEdit] Disabling WorldEdit v7.1.0;8e55131
[20:06:15 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[20:06:15 INFO]: Saving players
[20:06:15 INFO]: Saving worlds
[20:06:15 INFO]: Saving chunks for level 'world'/overworld
[20:06:15 INFO]: Saving chunks for level 'world_nether'/the_nether
[20:06:15 INFO]: Saving chunks for level 'world_the_end'/the_end


and so on ad infinitum

**Comment by AlexProgrammerDE** [comment]
@FreshSoul there are two eroors and two reasons:
1. Worldedit v7.1.0 support only 1.15-1.13 (https://dev.bukkit.org/projects/worldedit/files)
So just delete all plugins and search for versions with support for your version.
2. You downgraded your maps. 1.15 settings cant be load in 1.12.
My advice: Delete all folders begining with `world`

**Comment by FreshSoul** [comment]
Starting jar file with 2GB of RAM.
Unable to access jarfile spigot-1.8-R0.1-SNAPSHOT-latest.jar
but i set the variable ENABLE_UPDATE to true

**Comment by FreshSoul** [comment]
and delete JAR_FILE variable

**Comment by FreshSoul** [comment]
@AlexProgrammerDE, how to delete bungeecord?

**Comment by slashwhatever** [comment]
Apologies for reviving this thread but I'm in a similar boat. New device on balenaCloud. New push of minecraft server. Same corrupt jar file.

Tried setting the ENABLE_UPDATE flag and restarting several times.

Still getting this:

`
07.02.21 22:36:03 (+0000)  mc-server  Error: Invalid or corrupt jarfile paper.jar
07.02.21 22:36:13 (+0000) Service exited 'mc-server sha256:39660aa3f72adf5b878721269a5a55d9f522e4e22839672a340ec18af49ac3c3'
07.02.21 22:36:14 (+0000) Restarting service 'mc-server sha256:39660aa3f72adf5b878721269a5a55d9f522e4e22839672a340ec18af49ac3c3'
07.02.21 22:36:14 (+0000)  mc-server  Setting device hostname to: balenaminecraftserver
07.02.21 22:36:14 (+0000)  mc-server  
07.02.21 22:36:14 (+0000)  mc-server  
07.02.21 22:36:14 (+0000)  mc-server  Starting balenaMinecraftServer...
07.02.21 22:36:14 (+0000)  mc-server  
07.02.21 22:36:14 (+0000)  mc-server  Forcing server update
07.02.21 22:36:15 (+0000)  mc-server  Downloading 1.16.5 build 465...
07.02.21 22:36:30 (+0000)  mc-server  Starting JAR file with: 1G of RAM
07.02.21 22:36:30 (+0000)  mc-server  Error: Invalid or corrupt jarfile paper.jar

`

...and it just loops this over and over.
